### ISSUE TITLE
Filament Style Bulbs

### ISSUE THREAD

**Issue by mitch7391** [kpsuperplane/homebridge-wiz-lan#10]
Hi @kpsuperplane, I just installed your plug-in to see how I like these lights. I do notice you say this is mostly for RGB bulb support, but was wondering if at any stage you will be looking at making the plug-in to better accept dimmable white temperature changing bulbs? 

As they currently show a colour palette in HomeKit and the colour temperature does not appear to actually work; it looks like you just use the colours.

**Comment by mitch7391** [comment]
@dotkrnl do you think this is possible in the future?

**Comment by dotkrnl** [comment]
Hi @mitch7391!  I only own A19 so I could not help for other models.  Thanks!

**Comment by mitch7391** [comment]
@dotkrnl cheers for the quick reply! Not that I have much experience, but do you have any guidance in how I could look into trying to work it out myself?

**Comment by dotkrnl** [comment]
@mitch7391 You can try `echo '{"method":"setPilot","env":"pro","params":{"mac":"YOUR_MAC_HERE","src":"udp","dimming":100,"state":true,"temp":2869}}' | socat - UDP-DATAGRAM:255.255.255.255:38899,broadcast` to see the error message, and adjust the parameters to see when it works.

**Comment by mitch7391** [comment]
@dotkrnl thanks for the help and sorry for the late reply. I have run that command and it seems to send a 'set' command for the lights. I tried it by changing to a 'dimming' of 50 and that is where I noticed a few things are wrong. In Homekit it will then display my light as 45% not 50% (I had already suspected some scaling issues through usage) and the colour temperature of 2869 I would expect to be quite a warm white; seems to turn my light more of a cooler white than it should be (homekit shows it has been set as warm white or actually an orange hue?). This is what my the command returns for me:

{"method":"setPilot","env":"pro","result":{"success":true}}{"method":"setPilot","env":"pro","result":{"success":true}}

**Comment by mitch7391** [comment]
Is there any 'get' type commands I can use to have it pull information from the light?

**Comment by fluidpixel** [comment]
Try the following, with the correct IP.

`echo '{"method":"getPilot","env":"pro","params":{}}' | socat - udp-datagram:192.168.1.20:38899 `

**Comment by mitch7391** [comment]
@fluidpixel I just ran the command and it returned the following:

{"method":"getPilot","env":"pro","result":{"mac":"a8bb509d0336","rssi":-57,"src":"","state":true,"sceneId":6,"speed":100,"dimming":23}}

I am wondering if the 'sceneId' is the 'cozy' scene I currently have it set to (seems to be the warmest white) and I actually have them set to 15% dimming in homekit, but this is returning feedback that they are set to 23% by the looks. Curious that it did not return 'temp'.

**Comment by mwwgithub** [comment]
> Try the following, with the correct IP.
> 
> `echo '{"method":"getPilot","env":"pro","params":{}}' | socat - udp-datagram:192.168.1.20:38899 `
> 
> Should give you a result similar to:
> `{"method":"getPilot","env":"pro","result" {"mac":"a8bb509eaad3","rssi":-53,"src":"","state":true,"sceneId":11,"speed":100,"temp":2700,"dimming":56}}`
> 
> The temp and dimming are obvious, not sure what the speed refers too, pulsing perhaps?

I imagine "sceneId" and "speed" refer to the corresponding dynamic "light mode" settings in the WiZ proper app.  Eg, "Party ", and the selected speed.

**Comment by paffi05** [comment]
Hi, I'm new to this whole GitHub and Homebridge thing... is there already a solution for WIZ Filament bulbs?
Thanks!!

**Comment by mitch7391** [comment]
They have always worked in this plug-in, they are just represented incorrectly as rgb lights.

**Comment by mitch7391** [comment]
Added in #32 :)
