### ISSUE TITLE
Still Reports as On When Unplugged

### ISSUE THREAD

**Issue by mitch7391** [kpsuperplane/homebridge-wiz-lan#11]
@kpsuperplane  I noticed something after testing out a Filament style bulb that I didn’t turn off but instead just unscrewed it from the lamp. In HomeKit it was still reporting as ‘on’ until I pressed off in the Home app; this makes me suspect that feedback status or polling is not properly implemented. Have you noticed these issues before?

**Comment by MoTechnicalities** [comment]
This is confirmed. The offline bulbs fail to report a "No Response" status in HomeKit. They continue to show the most recent state prior to disconnect.

**Comment by mitch7391** [comment]
@MoTechnicalities is there any plan to fix this functionality? Or is it intentional? It makes more sense for it to report correctly that it has ‘no response’ if the device is unreachable.

**Comment by muzzymate** [comment]
I like the idea of reporting "No response" if the device is offline to communicate to the user that the bulb is uncontrollable and can not be turned on.

**Comment by mitch7391** [comment]
@dotkrnl or @kpsuperplane do you think this is possible for a future update?

**Comment by kpsuperplane** [comment]
Unfortunately I no longer have any wiz bulbs, but happy to accept any PRs if someone wants to do the work

**Comment by mwwgithub** [comment]
> Unfortunately I no longer have any wiz bulbs, but happy to accept any PRs if someone wants to do the work

What a shame.  I just started using your plugin and other than this bug, it has further increased the value proposition of the Philips branded WiZ bulbs available at Home Depot.

If I ship you a bulb would you consider continued improvements to your plugin?

**Comment by tbelcher** [comment]
> Unfortunately I no longer have any wiz bulbs, but happy to accept any PRs if someone wants to do the work

@kpsuperplane would you be able to walk me through the plugin and how it works?  I'd be willing to mess around with it, but don't have a strong background in Homebridge plugins.

**Comment by mitch7391** [comment]
These now report as 'No Response' like they should when powered off at the switch thanks to #32; closing out!
