### ISSUE TITLE
Instructions weren't exactly clear with how to connect Wiz lights

### ISSUE THREAD

**Issue by jmarmstrong1207** [kpsuperplane/homebridge-wiz-lan#110]
It didn't specify if I needed to reset the connection from the Wiz app in order to connect to Homebridge. I assumed this was the case, but it was not; You need to have the lights connected to the Wiz app for Homebridge to work.

I suggest adding this specific detail in the README.md so it doesn't confuse others and it makes it more user-friendly. It took me an hour of unnecessary work

**Comment by arminf82** [comment]
For me it was the option in the wiz app "Allow Local Communications". This option needs be turned on to have homebridge find my devices.

**Comment by kpsuperplane** [comment]
Thank you for the input, I have updated the readme!
