### ISSUE TITLE
Device Name

### ISSUE THREAD

**Issue by chrisbl01** [kpsuperplane/homebridge-wiz-lan#12]
@kpsuperplane first of all thanks for a pretty awesome plugin!  Since I’m pretty new to home bridge I may have missed something but is there a way for the plug-in to pull the name given in the Wiz app to then be reflected in HomeKit?  Or some sort of way for the names to not drop out of HomeKit once I’ve set them.  Problem being I have 19 of these wiz lights and whenever there is an update to the plug-in or even the confit-ui plug all the names drop out and so begins the tedious process of re-labeling them.  If there is another solution somewhere I may have not seen either by a setting or another plug-in I’d love to know.

**Comment by kpsuperplane** [comment]
Hi @chrisbl01, unfortunately I have not been able to find a way to grab the name. The names shouldn't be dropping out though...
