### ISSUE TITLE
Wiz Dimmer Switches

### ISSUE THREAD

**Issue by OzBarge** [kpsuperplane/homebridge-wiz-lan#121]
Trying to add Wiz Dimmer switches - only get this error:
Unknown device ESP01_DIMTRIACS_01, skipping...

How can I add these dimmer switches?

**Comment by kpsuperplane** [comment]
Unfortunately switches aren't supported by this plugin and I don't have the bandwidth to add support for them right now. Please feel free to submit a pull request though
