### ISSUE TITLE
Wiz plug ESP25_SOCKET_01 is not recognized

### ISSUE THREAD

**Issue by Mobidick1112** [kpsuperplane/homebridge-wiz-lan#123]
All bulbs in my room are recognized, but the Wiz plug is not recognized. However, the version from nikolas-schwarz-homebridge-wiz-net is able to identify the plug ESP25, but not the bulbs. A mix of both codes would be interesting, but I don't know how to do it.

**Comment by MoTechnicalities** [comment]
I've seen very little improvement to the plugin by kpsuperplane lately, and that's his prerogative.
On the brighter side, almost all WiZ products should get HomeKit support through matter, hopefully sometime soon. I'm just not sure how the change to matter support will affect my ability to directly set WiZ scenes through KomeKit SSH shortcuts.

**Comment by kpsuperplane** [comment]
Resolved by #118. @MoTechnicalities I too hope WiZ gets official support soon, unfortunately I just don't have the energy to regularly keep this plugin updated

**Comment by MoTechnicalities** [comment]
I and I'm sure a lot of other people are grateful for all you've done. WiZ should be paying you for all the extra bulbs people have purchased because YOU gave them HomeKit abilities through your plugin.

**Comment by Mobidick1112** [comment]
Thanks for your help to solve the issue.

A very nice day
