### ISSUE TITLE
Keep bulbs network ready!

### ISSUE THREAD

**Issue by MoTechnicalities** [kpsuperplane/homebridge-wiz-lan#127]
Hello, @kpsuperplane,
I have one issue that I hope you can tackle if possible.

If the bulbs are not used for a little while (not sure exactly how long) they seem to go to sleep on the network, thus making them slow (nearly 7--10 seconds) to respond to Siri, or in the case of my Pico remote button press, I have to wait that long before pressing the button again. Any way to have the plugin keep them awake?

**Comment by kpsuperplane** [comment]
I haven't experienced this, so I'm not sure how I could test it. I'm also not sure what would cause the bulbs to "wake up", would a "getPilot" do the trick? Or would I have to try to set something?

**Comment by MoTechnicalities** [comment]
A getpilot would have been my first guess. Perhaps a beta with an ability to set the request to do it every specified so often, I can see what happens.

**Comment by kpsuperplane** [comment]
Let me know if this helps haha

**Comment by kpsuperplane** [comment]
Actually make sure to use 3.2.5, 3.2.4 failed to publish

**Comment by MoTechnicalities** [comment]
OK. 3.2.5 is up and running! Let's give it a couple of days to see if there are any improved responses.

**Comment by MoTechnicalities** [comment]
So this is works as expected. However, logging all these pings is unnecessary and should be reserved for troubleshooting mode.

**Comment by MoTechnicalities** [comment]
Getting a tone of these unnecessary messages every ping.

![image](https://user-images.githubusercontent.com/68468472/212771262-94a5a73f-795b-4b2e-b2ce-3db3c0a87991.png)


Needn't say any more.

**Comment by krozgrov** [comment]
I am seeing the same issue with the log messages.
