### ISSUE TITLE
Removing bulb does not remove from plugin

### ISSUE THREAD

**Issue by Lologrampersand** [kpsuperplane/homebridge-wiz-lan#13]
I replaced a WIZ downlight with another WIZ downlight and the old bulb still shows up in both Homebridge and Homekit. Even if removed from Wiz app, it remains.

**Comment by mitch7391** [comment]
Are you using config-ui-x? You may be able to remove this device through the Homebridge settings; there is a setting for it.

**Comment by kpsuperplane** [comment]
Unfortunately there really isn't a way for the plugin to detect the difference between a bulb being off and a bulb being removed. By removing the bulb it'll break any presets/scenes/whatnot associated with it.

**Comment by Fernyman79** [comment]
@kpsuperplane What do you mean by break? HomeKit removes devices from automations too, if you delete them from home.

**Comment by kpsuperplane** [comment]
I meant that removal of bulbs on disconnect (eg loss of power) would cause the bulbs to disappear from any automations and scenes permanently, even if the bulb came back online later

**Comment by Fernyman79** [comment]
@kpsuperplane Got it. In the future it would be awesome if there was a way for the plugin to detect if a bulb has been deleted from the wiz app and automatically remove it from HomeKit as well.

@Lologrampersand I have managed to clear my removed bulbs by clearing cachedAccessories. Unfortunately this process will reset all of your homebridge accessories. You'll have re-enter any custom names, room allocations, and automations.

**Comment by Martynet** [comment]
Hi everyone, I had similar issue as above... Basically I installed Wiz plugin and the Light appeared in Homekit immediately and was working fine... But there was a "crack" in the light and seller sent me a replacement. After replacing the light, new one popped in my Homekit automatically and worked perfectly. But I wasn't sure how to remove the old one, as there was no option to remove it in Homekit app. Now I know that I have to remove it in Accessories section in Homebridge web page, but I didn't know that before... And I'm not sure exactly what I did, but both lights are gone now. I tried everything to bring it back, but no luck. I even deleted the Wiz app on my phone and completely re-installed whole Homebridge on my Synology NAS. But still no luck. Ring doorbell is working fine... The light works fine in Wiz app. It works in both Google and Alexa apps... The only place it doesn't work is Homebridge. It's making me crazy now :) If anyone can help, I'd really appreciate it. Thank you

**Comment by MoTechnicalities** [comment]
@kpsuperplane You may not have bulbs any more. But you know your work better than anyone else here. And your obviously pretty good at figuring things out. At least give us a way to remove unnecessary bulbs from the cache of your app if we don't need them anymore, without having to reseting all of our HOOBS accessories.

**Comment by mitch7391** [comment]
@MoTechnicalities does HOOBS not give you the option in the settings to individually remove cached accessories like Homebridge does?

**Comment by MoTechnicalities** [comment]
> 
> 
> @MITCH7391 does HOOBS not give you the option in the settings to individually remove cached accessories like Homebridge does?

If I setup an eWeLink plugin device, then I can remove that device from HOOBS and HomeKit via the HOOBS eWeLink plugin.
But there is no way to remove a WIZ light bulb from HOOBS and HomeKit via the WIZ pluggin! Deleting a light bulb in the WIZ phone App makes no difference! If you do, the light bulb still remains listed in HOOBS and in HomeKit without delete options.
You can hide the device in HOOBS but not HomeKit. In HomeKit I had no choice but to create a room called Void and move the icon for the light bulb to that room because there is no way to delete it. Also, hiding it in HOOBS does not hide it in HomeKit.

The plugin must give us a way to delete it from its cache, without totally resting everything and having to set them all up from scratch, but it does not!

**Comment by mitch7391** [comment]
Yeah sorry I am not sure how to help you without deleting the accessories and persist folders through a command which I believe is the same as the HOOBS method which resets all accessories. How many times are you having to do this? I mean if you have done it once (I know you shouldn’t have to), then you you should be good right? 

Personally I am really not a fan of HOOBS at all which is marketed at being the super easy solution for people at a marked up price, but then limits some easy functions like the cached accessory thing I mentioned previously. I have had a heap of issues trying to fault find some code I have on GitHub for a user that has HOOBS and could not do half of the fault finding needed until they gave up. Anyway...

I understand your frustration about not being able to get new features on this plug-in but we all need to understand that these are all maintained by regular people who do this out of their free time for no return other than to make people happy; they don’t need to maintain their plug-ins at all. I’d love to see some new features on this and it’s even getting me thinking about learning how to make a plug-in myself. But the developer has told a few of us several times that they do not maintain this plug-on anymore sadly.

**Comment by jeanofthedead** [comment]
@MoTechnicalities I'm not sure how different the HOOBS interface is, but I'm assuming you've already tried removing the cached accessories (see screenshot)?

![image](https://user-images.githubusercontent.com/56093335/104543356-26602a00-55da-11eb-9d31-29fc045cead2.jpeg)

**Comment by MoTechnicalities** [comment]
Personally I think that the plugin developers shouldn't have to build the ability to delete devices into their individual plugins. There should be a standard method under the system dashboard. HOOBS doesn't offer one... Yet.

**Comment by Martynet** [comment]
> Hi everyone, I had similar issue as above... Basically I installed Wiz plugin and the Light appeared in Homekit immediately and was working fine... But there was a "crack" in the light and seller sent me a replacement. After replacing the light, new one popped in my Homekit automatically and worked perfectly. But I wasn't sure how to remove the old one, as there was no option to remove it in Homekit app. Now I know that I have to remove it in Accessories section in Homebridge web page, but I didn't know that before... And I'm not sure exactly what I did, but both lights are gone now. I tried everything to bring it back, but no luck. I even deleted the Wiz app on my phone and completely re-installed whole Homebridge on my Synology NAS. But still no luck. Ring doorbell is working fine... The light works fine in Wiz app. It works in both Google and Alexa apps... The only place it doesn't work is Homebridge. It's making me crazy now :) If anyone can help, I'd really appreciate it. Thank you

BTW, all my problems got solved after restarting my router :)
