### ISSUE TITLE
Possible to blacklist certain devices?

### ISSUE THREAD

**Issue by jeanofthedead** [kpsuperplane/homebridge-wiz-lan#134]
Hi, is it possible to only add certain entities to HomeKit through this HB plugin? I have a few LED strips that support the new Matter protocol and have been added directly to HomeKit. I would prefer for them to not show up in this plugin, if that makes sense. Thanks.

**Comment by Terabyte1385** [comment]
Yes, we need this. I’ve just got some GU10 bulbs and added them via Matter and now the also show up in the plugin with no way to remove.

**Comment by MoTechnicalities** [comment]
Agree! They should however remain able to be controlled using SSH direct commands through this plugin. (See #106)
