### ISSUE TITLE
Way to automatically move a light from one room back into it's original room

### ISSUE THREAD

**Issue by afmmolina** [kpsuperplane/homebridge-wiz-lan#146]
I noticed that lights start having issues and becoming unresponsive after a while in specific rooms they are assigned to. This seems to mainly be an issue when using the WizClick remote. For example, you use a wiz-remote to turn on lights in a room and only 2 or 3 of 4 might turn on. One quick fix for this is to simply move one light in the affected room to another room (in the wiz app), and then back again. This seems to magically make all the lights respond properly once again. 

Is it possible to add a feature for this to automatically happen at a certain interval? Is it possible to even see room assignments within wiz-lan?

**Comment by kpsuperplane** [comment]
wiz-lan has no information about room assignments unfortunately
