### ISSUE TITLE
Is this plugin dead?

### ISSUE THREAD

**Issue by aarnaegg** [kpsuperplane/homebridge-wiz-lan#149]
Just curious if this is being maintained anymore.

**Comment by Vic-Firth** [comment]
Based on the description I think he probably won't be updating it a whole lot. I have no clue how to code or how it works. I wish I could make it work better for my situation or that someone could.

**Comment by slambert** [comment]
You may not be as familiar with open source code – it's usually all volunteer. The last update to the code was 6 months ago. That is for sure not dead. It may not happen at the pace you like – I relate, I'd like to see more development too and wish I could contribute – but at this point it is certainly not dead.

**Comment by kpsuperplane** [comment]
I unfortunately have neither the time to actively maintain this nor the newer bulbs to test with. However, I'd be more than happy to accept any pull requests if you're willing to take a stab!
