### ISSUE TITLE
EHOSTDOWN -- Node Problem?

### ISSUE THREAD

**Issue by SovereignGFC** [kpsuperplane/homebridge-wiz-lan#151]
![image](https://github.com/kpsuperplane/homebridge-wiz-lan/assets/7810520/3c9d5a78-b738-4b2d-86c8-c43b14d613d6)
I receive this error when trying to send commands using the Home app/shortcuts on my iPhone.

Note that Google commands to these bulbs work just fine, so it's definitely either HomeBridge or the plugin.  Wyze through HomeBridge works fine.

I've Googled "EHOSTDOWN" and got...a ghost town (heh) of results with regard to this plugin's usage of that term (as in, none at all).

It seems to be a Node.js specific error as other HomeBridge plugins have thrown it at times like [this example](https://www.reddit.com/r/homebridge/comments/vexh9n/random_ehostdown_error_primarily_w_kasa_devices/).  [This](https://stackoverflow.com/questions/30458800/how-can-i-catch-an-ehostdown-socket-error-when-creating-an-http-request-with-ioj) example also resolved to a bug in Node.

**Comment by kpsuperplane** [comment]
This means that the plugin is lost its connection to the bulb, I would check your network settings
