### ISSUE TITLE
Bulbs No Longer Found

### ISSUE THREAD

**Issue by jeanofthedead** [kpsuperplane/homebridge-wiz-lan#17]
Hey there - I know you've moved on to the Philips Hue ecosystem, but I'm trying to get my Wiz lights working with Homebridge. They were working fine in HOOBS, but after switching over to the official Homebridge Raspberry Pi OS, and installing your plugin, nothing is showing up. Could you possibly see if anything has changed with their API, or if something was broken in the more recent Homebridge updates? I appreciate your help.

**Comment by kpsuperplane** [comment]
Hey, unfortunately I can't provide much support at this point. https://github.com/victori/homebridge-wiz-lan seems to have a working build updated for Costco bulbs, so feel free to try that out.

**Comment by Polishdad5** [comment]
Sorry. Completely new to this. His build seems be the exact same install as yours.  How do I install his updates?

Thanks!

**Comment by kpsuperplane** [comment]
Closing due to new V3.0.0 update which should fix most things. Feel free to open another issue if problems persist!
