### ISSUE TITLE
New user troubles

### ISSUE THREAD

**Issue by Fredvs79** [kpsuperplane/homebridge-wiz-lan#19]
Hello,
  I realize this plugin may be deprecated, so I'm hoping that some of the users might be able to offer me some guidance.

I bought 4 LED RGB WIZ high hat downlights for my living room from HomeDepot. I set them up in the WIZ app, and I paired them to my google account. The google nest I have controls these lights fine. But I have an iPhone, then I got an Apple watch, and found that using Siri would be pretty useful, but WIZ isn't HomeKit approved. So, all new to me, I bought my first Raspberry Pi (Zero WH), and installed homebridge, then installed this homebridge-wiz-lan plugin. After that I was able to add the bridge to Homekit on my phone. However, in HomeKit when I go to "home settings" and select the pi homebridge, unlike my philips Hue bridge which has several lights connected to it, the pi homebridge has no lights attached to it. So nothing shows up in HomeKit.  Also, when I go to http://homebridge.local/accessories there are no detected bulbs. I made sure that the lights were on, and set to cool white, and tried rechecking my steps, but I don't see why the bulbs aren't just 'there'. 

I thought the bulbs would just be detected, either in homebridge, or in HomeKit when I add the homebridge. I'm wondering if I'm missing an obvious step or if this just requires higher-level troubleshooting? While I am happy to tinker to make things work, I don't have an abundance of patience, nor do I expect it from the community if the developer has already moved on. I would have been happy if WIZ lights would work, but perhaps I'll just have to stick with HUE. 

If anyone has any tips or suggestions for me as a noob, please post, and thanks for your time.

**Comment by kpsuperplane** [comment]
Hey there,

Unfortunately it does appear that some software update from Wiz broke this plugin a while. 

My best suggestion is to look into setting up homeassistant instead; they have an actively supported wiz implementation https://github.com/sbidy/wiz_light

Alternatively, it seems there exist a couple forks of this project that seem to work. 

https://github.com/chrisbl01/homebridge-wiz-lan
