### ISSUE TITLE
detected only one of 4 light bulbs in my house

### ISSUE THREAD

**Issue by vitata78** [kpsuperplane/homebridge-wiz-lan#2]
not sure why - how can I detect the others?

**Comment by newt10** [comment]
which version of node/npm are you using?

**Comment by vitata78** [comment]
Node.js Version | v12.16.1
Npm Version | v6.14.1

**Comment by kpsuperplane** [comment]
Hey @vitata78, this plugin relies on bulbs responding to broadcast messages sent to 255.255.255.255. Is it possible your bulbs are on different subnets? 

Alternatively, you can manually specify the IP addresses of your Wiz bulbs using this config:
https://gist.github.com/kpsuperplane/e30e7eda22c9522be7b9641ad6364c85

**Comment by vitata78** [comment]
oooh you're right.. these bulbs were on different subnets, thanks for the hint!!
