### ISSUE TITLE
Control RGB and White independently

### ISSUE THREAD

**Issue by jappyjan** [kpsuperplane/homebridge-wiz-lan#23]
I have a WIZ ceiling light which consists of a white (warm/cold) main light and an rgb led strip.
Both are meant to be controlled independently (rgb lighting the ceiling, white lighting the room).

Can you add an option to control these independently via HomeKit? 
Having two devices would absolutely be an option, this does not have to be combined into one HomeKit/Homebridge device

**Comment by kpsuperplane** [comment]
Sorry for the super late reply. If this is still relevant, which model of light is this? I'm having trouble finding a Wiz light that has both color strip and white light built in
