### ISSUE TITLE
Takeovers of this work.

### ISSUE THREAD

**Issue by MoTechnicalities** [kpsuperplane/homebridge-wiz-lan#31]
It seams that the founder of this valuable work has abandoned it.🥺 Isn't it possible for a person with interest in this repository to simply create a new branch, rename it and improve it, then simply let us know what the new branch is to follow?🤔 I really wish I could! But currently working up to 80 hours/ week! Just not enough time to devote! I really like these bulbs and LED strips! I hope someone can do it soon.🖖🏼

**Comment by mitch7391** [comment]
Created a similar issue just today in #29, hopefully if this gains more interest someone might pick it up...

**Comment by kpsuperplane** [comment]
I'll have some exciting updates to share by midnight PST tonight :)

**Comment by kpsuperplane** [comment]
It might involve the fact I just purchased 3 wiz bulbs from Home Depot

**Comment by MoTechnicalities** [comment]
> It might involve the fact I just purchased 3 wiz bulbs from Home Depot 

This is great news. Yet, if I may ask, Is it at all possible to duplicate this work to support the Feit Electric bulbs that Costco now sell?

**Comment by kpsuperplane** [comment]
Unfortunately without those bulbs in hand I will not be able to figure out how they work and adapt the plugin to them. 

However, I will say I am rewriting this plugin to be much more developer friendly so hopefully that work shouldn't be too hard for someone else to do!

**Comment by MoTechnicalities** [comment]
> Unfortunately without those bulbs in hand I will not be able to figure out how they work and adapt the plugin

How much of a donation do you need? Feit Electric is also available on Amazon.

**Comment by kpsuperplane** [comment]
Some quick research tells me Feit bulbs are Tuya based - have you tried this plugin
? https://www.npmjs.com/package/homebridge-tuya

**Comment by kpsuperplane** [comment]
https://github.com/kpsuperplane/homebridge-wiz-lan/pull/32
