### ISSUE TITLE
No loaded plugin could be found for the name

### ISSUE THREAD

**Issue by dronenb** [kpsuperplane/homebridge-wiz-lan#34]
Using version 3.0.0 of this plugin installed via npm, I encounter the following message:

A platform configured a new accessory under the plugin name 'WizSmarthome'. However no loaded plugin could be found for the name!

I think Homebridge is expecting WizSmartHome to match homebridge-wiz-lan.

**Comment by a7medkamel** [comment]
same here: 

```
[24/02/2021, 21:07:50] [WizSmarthome] Adding new accessory: Wiz Tunable White Bulb ------
[24/02/2021, 21:07:50] A platform configured a new accessory under the plugin name 'WizSmarthome'. However no loaded plugin could be found for the name!
```

**Comment by kpsuperplane** [comment]
This initially happened to me too but after restarting the server it went away. Is it actually causing anything to not work?

**Comment by dronenb** [comment]
@kpsuperplane I believe this issue only occurs when the plugin first creates devices, thus every time a new device is automatically discovered, it throws this issue. It does not impede any functionality, just clutters the logs, thus its super low priority, but an issue nonetheless.

**Comment by mitch7391** [comment]
My fix for this was to uninstall the plug-in and removed the config; then re-install with the correct config and it should be all good. 

I think this issue occurred due to the accidental change of platform name in the required config from `v2.2.0` to `V3` (beta accidentally rolled out before merge?) and then back again to `v3.0.0`.

**Comment by ppapajohn** [comment]
@mitch7391 thanks for the suggestion. Unfortunately the issue still appears on my side. Remover plugin, deleted config (and I have to rename everything again unfortunately..) but the issue still appears.. 
[2/26/2021, 2:12:30 AM] A platform configured a new accessory under the plugin name 'WizSmarthome'. However no loaded plugin could be found for the name! 

Please note that I have added the plugin as a child bridge, in case this affects anyhow. Any ideas? 

btw, irrelevant to this post: Is there any way to save somehow the names of the bulbs in the config file and on top the names to be correctly advertised to homekit? Each time I have to remove the plugin and add it back again, I have to do everything from scratch, i.e. rename the bulbs in Homebridge and in Homekit!. :(

**Comment by mitch7391** [comment]
Child bridge could be affecting it, I have not set mine up as one yet. Completely remove the plug-in and config, then remove the bridge in homebridge ui settings and unpair it from your HomeKit. Then reinstall, make sure you are using the correct config and set up your child bridge again. I think this should sort you out...

**Comment by ppapajohn** [comment]
Thanks @mitch7391. Removed the plugin and the config completely. Added it again and it appears that when initially loaded the following message appears for each of the bulbs identified: 
**"A platform configured a new accessory under the plugin name 'WizSmarthome'. However no loaded plugin could be found for the name!"**

Following this initial time, the plugin seems to work normally after the 1st homebridge server restart. 

Haven't tested it yet, when the plugin is configured as a child bridge... I think I will skip this for another time as renaming several bulbs from scratch is very time consuming. :)

**Comment by mitch7391** [comment]
Yeah I am waiting until my week off work until I start the child bridges, I did it when it first rolled out and it destroyed my HomeKit and had to painfully put it all back; since then the issue I had has been fixed haha
