### ISSUE TITLE
[BUG] TW Light Reverts to RGBW Selector

### ISSUE THREAD

**Issue by mitch7391** [kpsuperplane/homebridge-wiz-lan#35]
I have a very curious one @kpsuperplane, originally these TW lights (model ESP56_SHTW3_01) showed only white selections and only the temperature wheel; once selecting from the temperature wheel the menu selection now displays colours and both a colour and temperature wheel. It seems to be stuck as an RGBW light now.

![4AACE873-3E36-4689-BE71-B53473EB4F5D](https://user-images.githubusercontent.com/40288237/109155951-32c7cd00-77ab-11eb-80c4-96d173e22321.png)
![F6E26D4B-1AF5-4578-A786-C5043204D5B4](https://user-images.githubusercontent.com/40288237/109155962-378c8100-77ab-11eb-932b-6b2ef4520f24.png)

This has not broken anything, but definitely a bug.

**Comment by paffi05** [comment]
I have the same problem with my filament bulbs ESP06_SHTW1_01

**Comment by kpsuperplane** [comment]
V3.0.1 should theoretically fix this, let me know if it does!

**Comment by mitch7391** [comment]
Looks fixed to me :) nice work! Thanks!
