### ISSUE TITLE
On/Off commands not working with dynamic settings

### ISSUE THREAD

**Issue by Judas2016** [kpsuperplane/homebridge-wiz-lan#4]
Hi,

Just setup the latest version of the plugin (v2.0.4) on latest version of home bridge (v0.4.53).  Plugin works with lights if if they are set via the Wiz app to use the "white" bundle of settings (warm, day, cool, night) or a set custom color (via app or home bridge).  If the bulbs are in any of the dynamic or simple setting bundles the lights will not respond to home bridge on/off commands but home bridge display the correct state (on/off). Weird thing is you can change the color of the bulb from one of the dynamic bundles to a fixed color via the home app, then the light will respond to on/off commands.

Is this a known feature gap?

**Comment by rloomans** [comment]
I have the same problem with a warm white (no colour) bulb.

@kpsuperplane do you have any ideas?

**Comment by iSub1** [comment]
+1

Installed Homebridge and then Homebridge Wiz Lan. Bulbs detected fine, I can see their status and I can change their colour (if they are already on) in the Home app but I cannot turn them on or off!

Anyone solve this problem yet?

**Comment by SkOODaT** [comment]
im seeing the same issues now with on and off, something has changed :S

**Comment by SkOODaT** [comment]
and mysteriously it started to work again 
client.startDiscovery(): socket:message From: 192.168.0.63 38899 Message: {"method":"setPilot","env":"pro","result":{"success":true}}

setPilot was failing every time

**Comment by OrigSorceror** [comment]
Same result.. Bulbs are being communicated with (status is being reported) but unable to to turn on/off or change brightness. 
Have restarted PC and Homebridge server. Suspect WIZ has changed something as they have migrated to a new app (which works fine). No errors in homebridge logs. 

Have noticed following in CLI though.

[7/16/2020, 6:59:11 PM] [WizSmarthome.API] client.startDiscovery: UDP Error: Error: bind EADDRINUSE 0.0.0.0:38900
    at dgram.js:339:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'bind',
  address: '0.0.0.0',
  port: 38900
}
[7/16/2020, 6:59:11 PM] Error: bind EADDRINUSE 0.0.0.0:38900
    at dgram.js:339:20
    at processTicksAndRejections (internal/process/task_queues.js:85:21)

**Comment by kpsuperplane** [comment]
Hello everyone, unfortunately @rloomans is correct in that this is a known feature gap. I unfortunately have not found a way to fix this, although PRs are always welcome. 

@SkOODaT @OrigSorceror I believe your issues may be fixed with Version 2.0.5, which integrates #7

**Comment by OrigSorceror** [comment]
@kpsuperplane  Yup i implemented that fix a few days ago and it works a treat with my A60's :)
