### ISSUE TITLE
Adaptive Lighting

### ISSUE THREAD

**Issue by iRayanKhan** [kpsuperplane/homebridge-wiz-lan#43]
Hello,

Homebridge v1.3.0 aded support for adaptive lighting. Any chance we could see it in the plugin?

**Comment by jakebellacera** [comment]
I see it working. Though, now I'm seeing these errors in the log:

> [homebridge-wiz-lan] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Comment by iRayanKhan** [comment]
> I see it working. I didn't do anything (aside from updating Homebridge).


It has to be manually added into the plugin. I don't see the option for this plugins lights, but I do for my other lights. Not sure how yours has it added, unless I missed something.

**Comment by kpsuperplane** [comment]
@iRayanKhan v3 of this plugin has support for adaptive lighting. Is it not showing up for you? https://github.com/kpsuperplane/homebridge-wiz-lan/pull/32/commits/8d914c5d47175ae8e8c90f0cdf8d02d5a51a75ad

**Comment by ntorres1964** [comment]
I am running Hoobs on a Raspberry Pi. My plugin Wiz Lan 2.2.0, on Hoobs 3.3.2, was working fine, until I upgraded to V3.0. It screw my system to the point I needed to reprogram all from scratch.  I saw today Hoobs 3.3.3 and Wiz Lan 3.0.1. Can somebody confirm if it is actually working? Thank you fro sharing.

**Comment by iRayanKhan** [comment]
> @iRayanKhan v3 of this plugin has support for adaptive lighting. Is it not showing up for you? [8d914c5](https://github.com/kpsuperplane/homebridge-wiz-lan/commit/8d914c5d47175ae8e8c90f0cdf8d02d5a51a75ad)

A few restarts, and a bulb power-cycle later, it shows up!

Thank you! I may get more Wiz bulbs now :)

**Comment by iRayanKhan** [comment]
> I am running Hoobs on a Raspberry Pi. My plugin Wiz Lan 2.2.0, on Hoobs 3.3.2, was working fine, until I upgraded to V3.0. It screw my system to the point I needed to reprogram all from scratch. I saw today Hoobs 3.3.3 and Wiz Lan 3.0.1. Can somebody confirm if it is actually working? Thank you fro sharing.

You should switch to the official home bridge image. The latest version of the plugin is working for me on the latest version of homebridge (1.3.1)

**Comment by ntorres1964** [comment]
Pardon my ignorance. How I switch to the official Homebridge image? That implies getting rid of Hoobs?

**Comment by ntorres1964** [comment]
Reading more...Hoobs 3.3.3 upgrade to Homebridge 1.3.1. Upgrading Hoobs should be enough?
