### ISSUE TITLE
Brightness

### ISSUE THREAD

**Issue by rasazu** [kpsuperplane/homebridge-wiz-lan#44]
Hi,
Any idea about this warning.??
This plugin generated a warning from the characteristic 'Brightness': characteristic was expected valid number and received NaN.

Versión de Node.js: v14.15.5
Versión de npm: v6.14.11
Bulbs: GU10 & A.E27

Regards, Ramon

**Comment by kpsuperplane** [comment]
@rasazu  do your bulbs support varying brightness?

**Comment by rasazu** [comment]
Yes... all of them... is strange becasuse just 3 of thems shows me the warning...

**Comment by kpsuperplane** [comment]
Please feel free to create a new issue if it's still happening, sorry for the super late reply
