### ISSUE TITLE
Missing Bulbs in Child Bridge Mode

### ISSUE THREAD

**Issue by jctull** [kpsuperplane/homebridge-wiz-lan#45]
I switched the plugin to child mode, but now only 3 of my 6 bulbs are showing up in HomeKit. My log shows, "A platform configured a new accessory under the plugin name 'WizSmarthome'. However no loaded plugin could be found for the name!" on startup, but I believe that was being logged before the change to child bridge.

**Comment by jctull** [comment]
Some of those missing bulbs showed up an hour or so later, but then one or two were no longer in HomeKit today. Unusual, probably will take this plugin out of child bridge mode until for now. Curious if this is happening for anyone else though.

**Comment by jeanofthedead** [comment]
Two of my bulbs were missing after switching to Child Bridge, but they appeared after restarting Homebridge. All is well now.

**Comment by kpsuperplane** [comment]
Apologies for the late reply, please create a new issue if this is still occuring

**Comment by jctull** [comment]
> Apologies for the late reply, please create a new issue if this is still occuring

I moved to home assistant with homebridge for Ring camera features. I believe things became stable for me before I made the switch, but not entirely sure at this time.
