### ISSUE TITLE
Light Strip manual toggle button

### ISSUE THREAD

**Issue by MoTechnicalities** [kpsuperplane/homebridge-wiz-lan#46]
The HomeKit On/Off status of the WIZ light strips does not update when I toggle the state with the manual switch, unless I leave the HomeKit room and come back in or leave the Home app and come back in. The WIZ App does update with a manual toggle. So, the Homebridge/HOOBS plugin is not properly evaluating and updating the state of WIZ devices to HomeKit. The manual switch on the LED strip is only a state toggle. It does not cut overall power to the device.

**Comment by kpsuperplane** [comment]
Duplicate of #47
