### ISSUE TITLE
Smart Plugs stopped working 

### ISSUE THREAD

**Issue by snippetsnake** [kpsuperplane/homebridge-wiz-lan#49]
For some reason my WiZ Smart Plugs stopped working after updating to the newest version. Any reason they would act out now?

**Comment by u0xpsec** [comment]
Same thing happened to me. They worked before and now the plugin just doesn't seem to find them.

**Comment by jkankare** [comment]
I'm having this same problem too...

**Comment by MeatG** [comment]
I too would be very pleased if this worked.
