### ISSUE TITLE
ST19 Bulbs work and reporting of bulbs powered off

### ISSUE THREAD

**Issue by muzzymate** [kpsuperplane/homebridge-wiz-lan#5]
I was gifted some Wiz RGB A19 bulbs recently and started using the plugin. Couldn’t be easier to get set up and running in Homebridge. Thank you!

Also picked up some ST19 soft white LED 40W (link below), not expecting them to work, but was pleasantly surprised that the plugin just discovered them and could control them out of the box. I know you said you will only be supporting the RGB bulbs but wanted to report in my experience for documentation:

With the ST19 bulb the following features work:
- Detection of brightness level
- Changing of brightness level
- Detection of bulb’s color temperature
- Detection and changing status of bulb on or off

What does not work:

- The plugin exposes the Homekit color picker and allows it to be changed in the Home app. However, this bulb’s color or color temperature is not actually changeable and the bulb seemingly just ignores the command. 

https://www.homedepot.com/p/Philips-Soft-White-ST19-LED-40W-Equivalent-Dimmable-Smart-Wi-Fi-Wiz-Connected-Wireless-Light-Bulb-555557/310289025

One thought:
I’ve noticed with both the A19 and the ST19 bulb that if they are turned off at the power switch, Homekit will only report it’s last known status. I’ve seen other plugins report powered off bulbs as off in Homekit. Perhaps if the plugin does not receive the heartbeat from the bulb in XX seconds or if it is not responding to pings, the status of the bulb is reported as off to Homekit?

**Comment by mitch7391** [comment]
This one should be good to close out now right @muzzymate and @kpsuperplane?

**Comment by muzzymate** [comment]
Closing out. Offline bulbs now report as "No Response" with #32     Thank you!
