### ISSUE TITLE
Homekit Automations with Wiz Plugin

### ISSUE THREAD

**Issue by tech4life2015** [kpsuperplane/homebridge-wiz-lan#52]
I have been running into some weird HomeKit shortcut automations with button presses. I create a automation to check if the light is on or off and based on that it turns it on or off. The automations rarely have a issue with turning the wiz lights off but turning on they always time out. I can manually turn them on and off. I was wondering if you have run into this issue before?

**Comment by kpsuperplane** [comment]
No I have not, did you resolve this?
