### ISSUE TITLE
No Response from Wiz Recessed Color and Turnable White Light

### ISSUE THREAD

**Issue by tech4life2015** [kpsuperplane/homebridge-wiz-lan#53]
I get erratic error messages and recessed lights not responding correctly either turning on or off. I don't seem to run into this issue with the Wiz light bulbs. Thoughts on if there is a difference between how the recessed lights and the normal light bulbs treated?

This is the light link i am having issues with https://www.homedepot.com/p/Philips-Color-and-Tunable-White-5-6-in-LED-65W-Equivalent-Dimmable-Smart-Wi-Fi-Wiz-Connected-Recessed-Downlight-Kit-555623/310289033

Let me know if you need me to gather logs to help troubleshoot.

**Comment by kpsuperplane** [comment]
Sorry for the super late response -- is this still happening?
