### ISSUE TITLE
Invalid JSON in an platform error message

### ISSUE THREAD

**Issue by tf64** [kpsuperplane/homebridge-wiz-lan#54]
Complete newbie here, basically a baby playing with scissors. Trying to get the wiz plugin to work using homebridge (HOOBS build). Using the "simple configuration" I get the following error:

**"Unable to save. Please fix the following errors. Invalid JSON in an platform."** 

- Wiz Lan: Version 3.0.2 (3/11/21)
- HOOBS: Version 3.3.5

I'm pasting into configuration field:

"platforms": [{
    "platform": "WizSmarthome",
    "name": "WizSmarthome",
}]

Perhaps someone could assist in identifying what I'm doing wrong? Thanks in advance!
![Screen Shot 2021-03-30 at 3 31 37 PM](https://user-images.githubusercontent.com/28816860/113203070-2bc02e80-9231-11eb-8f2c-0cc8a5f9fa80.jpg)

**Comment by woundedknee45** [comment]
I have exactly the same problem.  
Wiz Lan: Version 3.0.2 (3/11/21)
HOOBS: Version 3.3.5

I searched for hours looking for an answer, and came here to post this issue, only to see that someone else posted the same issue.  I tried different combinations of both the simple configuration and full configurations, and no matter what I put in I get the same "Unable to save. Please fix the following errors. Invalid JSON in an platform."

The only thing I can put in and not get an error is what what there right after I installed the plugin, which was "{}".  Anything else gives me the invalid JSON error. 

Any help or guidance would be appreciated.  Thank you!

**Comment by MoTechnicalities** [comment]
In HOOBS, I think you sould just have the below pasted in the spot shown:
`[{`
`    "platform": "WizSmarthome",`
`    "name": "Wiz"`
`}]`

**Comment by woundedknee45** [comment]
Mo, thanks for the comment, you helped me get it to work. 

I had tried that before posting my question, and it didn’t work. BUT, I was reading your comment on my phone and decided to try it again, this time from the mobile interface on my iPhone, and it worked!  I’m guessing there is some issue with chrome and the Hoobs interface that is not there when using the mobile interface with safari on the iPhone. Weird, but it worked!  Thanks!!

**Comment by tf64** [comment]
@MoTechnicalities thank you so much! That worked!
