### ISSUE TITLE
Help !!

### ISSUE THREAD

**Issue by DUSKULL** [kpsuperplane/homebridge-wiz-lan#55]
Hi,
I have never used Homebridge before and have installed it with docker on my NAS
I am trying to add around 30 Wiz bulbs but just cannot get this to work
I have added the plugin but get stuck at the sample code.
I pasted it into the config file, changed the port and IP address to mine then added all of the bulbs IP addresses.
When I go to Homekit I don't see anything.  I have clicked add accessory but it asks for a qr code to be scanned.
Can you give easy instructions on how to use this with homier and detect my bulbs
Thanks

**Comment by MoTechnicalities** [comment]
The sample code is wrong!
Refer to one of the closed issues about this.

I don't know why the owner doesn't update the instructions here on GitHub.

**Comment by MoTechnicalities** [comment]
I just made a pull request to have the sample config fixed.

**Comment by DUSKULL** [comment]
Thanks
