### ISSUE TITLE
Have to ask siri twice for the lights to turn on

### ISSUE THREAD

**Issue by JackSetaro** [kpsuperplane/homebridge-wiz-lan#64]
The lights only turn on if I ask siri twice. The first time she says "sorry I did not get a response from your devices" Is this an issue can that be fixed? Thank you.

**Comment by rmartella000** [comment]
Same problem here

**Comment by kpsuperplane** [comment]
Does this happen often? Unfortunately homekit gives me a very limited amount of time to complete the request, and it's possible there were some delays in the network

**Comment by rmartella000** [comment]
It happens every time. It works fine from the home app but I have to do it twice with Siri and shortcuts.

**Comment by anshumanbhatia** [comment]
was there any move on this? I have the same problem

**Comment by ipaqmaster** [comment]
On homebridge v1.3.5 here. iOS 15.1.1 on an iPhone 12 Pro. Also having this problem for some things on homebridge for the past few months.

Very frustrating having to repeat to Siri to do something and Siri instantly gives up with response `The XYZ is not responding.` like the phone didn't even try. Immediately repeating the vocal command works instantly as desired the first time.

UniFi WiFi network with great signal strength to all devices including the phone and no noise on the channels the APs are configured for (Not a WiFi networking related problem)

This problem happens consistently for me after the phone screen has been off for at least 30 seconds. Long enough for the phone to enter a power saving sleep and stop responding to pings over WiFi.

It would be nice to solve. My home lights (LIFX, which are **not** on homebridge but rather added directly to HomeKit) never exhibit this issue and always work first try. I've only experienced this issue with homebridge appliances.

**Comment by kpsuperplane** [comment]
Hey @ipaqmaster, are you experiencing this with other homebridge plugins?

**Comment by ipaqmaster** [comment]
Hi kpsuperplane, I see your above comment mentioning how little time Homekit gives them little time to run and it does have my attention.

I have a few cmdSwitch2 modules and tthat module just runs shell commands. Very easy to use for people who spend a lot of time in shells.

- I have example 1 which just runs `sudo ether-wake aa:bb:cc:11:22:33` to turn on my desktop. And that always works fine and responds near instantly given the nature of WOL magic packets. Never an issue not even once.

- I have a second example which turns on the aircon, its command is `ssh remotehost irsend send_once aircon on` to transmit an infrared signal for the aircon. This one despite being the same module  almost always needs to be said twice however also responds in about 1-2 seconds. (1.147s in my test just now in the shell, not very long). Yet this one always fails on the iPhone for some reason.

- At the same time though... I have a third example which uses the same above command but to toggle the TV on/off also using the same infrared syntax as above.

- Then a fourth one which does the same for the audio system in the same room.

These last two examples _never_ exhibit this "not responding" issue and always work, taking the same 1-2 seconds as the aircon command if not sometimes longer. Yet that aircon command the iPhone always struggles to execute.

The homebridge server runs on the hypervisor as a CentOS 7 VM, it runs 24/7 and has no sleep state. (Unless you're referring to some internal sleeping state which homebridge enters after some idle time)


---

Even just now with my phone asleep -- I was able to say "turn on the TV", then "Turn on the surround" and those worked, then saying "Turn on the aircon" responded instantly saying it's not responding despite being the exact same `ssh remoteHost sudo irsend send_once x y` syntax as examples 3 and 4, which worked just now.

I don't know why it doesn't like the cmdSwitch2 aircon switch yet.

**Comment by ipaqmaster** [comment]
Ah sorry kpsuperplane, I didn't realize what tab I was in making this post, this isn't relevant to your module at all! I'll go and put my comments in the appropriate repo.

**Comment by kpsuperplane** [comment]
Thanks for the super in-depth response! As you mentioned, Homebridge does have an internal timeout, and while it isn't long, it's certainly noticeable (on the order of seconds). So when you say "siri instantly gives up" that probably means it's not the internal homebridge timeout that's going on here, especially since a repeated command works instantly!

This suggests something wonky is going on with your server (or homebridge install).

**Comment by kpsuperplane** [comment]
Oh, LOL. No problem haha

**Comment by ipaqmaster** [comment]
Yeah I can't believe it, so sorry about that lmao. But the information you've provided me with is still helpful and relevant to my issue so I'll look into potential timeouts either down the line or on homebridge itself. Thanks again for your time.
