### ISSUE TITLE
Enhancement request: Any chance that Dynamic modes could be added?

### ISSUE THREAD

**Issue by jeffmcnabb** [kpsuperplane/homebridge-wiz-lan#65]
Thank you for your work on this plugin! Just curious if there's any feasibility that Dynamic lighting modes could be added? Is  this feature something dependent on the Wiz app, and not accessible through local processes?

**Comment by jeanofthedead** [comment]
I'm not the dev, but if you're using Hubitat or the like, you can activate the preset Wiz scenes using either the set setEffect command (0-32), or setting the ColorTemperature (CT) to 6000-6032. This is how I have my scenes set up in Hubitat, and have made virtual switches that are shared to HomeKit via Homebridge!

**Comment by slbloomer** [comment]
With Hoobs v 4.0.92 when updating configurations (adding ip addresses of each bulb), upon saving, all configuration details went away, replaced with default settings.

**Comment by kpsuperplane** [comment]
I like this idea, but am struggling to think of how this would look in homekit. What kind of homekit control would be appropriate for this?
