### ISSUE TITLE
Hoobs 4

### ISSUE THREAD

**Issue by sergioloera** [kpsuperplane/homebridge-wiz-lan#66]
Looks like the new hoobs doesn't play well. Just keeps wanting to install and shows no configuration page to enter settings.

![wiz-lan](https://user-images.githubusercontent.com/3608138/125203883-99c0bc80-e248-11eb-8996-28ed2664c30c.jpg)

**Comment by slbloomer** [comment]
Similar, but I was actually able to enter configurations, but on saving, they (all my changes) went away.

**Comment by BMDan** [comment]
Configuration in Hoobs 4 is located under Config->Advanced (i.e., http://hoobs./config/advanced if you're on Hoobs).  It _should_ be available on this page, too, but at least the Config->Advanced approach will give you the ability to set/update the config.

**Comment by Texas84** [comment]
I followed the steps in Config->Advanced and I went to save my changes and it also went away after hitting save. No configurations saved. Maybe a separate Configuration Tab with easier steps like other plugins for those of us that are not that tech savy?

**Comment by kpsuperplane** [comment]
Should be fixed in the latest update :)
