### ISSUE TITLE
Value expected valid finite number

### ISSUE THREAD

**Issue by Diegoupnorte** [kpsuperplane/homebridge-wiz-lan#70]
Hello, im using wiz-lan with Hoobs 4 but I keep receiving this error message.

@Brightness] characteristic value expected valid finite number and received "NaN" (number)

any ideas why this happens?

**Comment by kpsuperplane** [comment]
No, sorry. Did this ever resolve itself?

**Comment by Roshanalexander** [comment]
@kpsuperplane Recently I've started seeing this issue as well. Continuous error in the log file.
[homebridge-wiz-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
