### ISSUE TITLE
Not working with Hoobs 4

### ISSUE THREAD

**Issue by leoxnv** [kpsuperplane/homebridge-wiz-lan#71]
Not working with Hoobs 4.  Cant save changes in config.

**Comment by ken-alt** [comment]
> Not working with Hoobs 4. Cant save changes in config.

same.

**Comment by JerryGarciaDeadhead** [comment]
Same. Running 4.0.1. Also can't save config. Running on HOOBS 3 everything just worked with no changing config defaults. It was great.

**Comment by FreeeG** [comment]
I have similar issues after upgrading from 3 to 4. Running HOOBS v4.0.109 to be presise.

**Comment by kpsuperplane** [comment]
Does the latest update fix this with hoobs?

**Comment by kpsuperplane** [comment]
@robkoehler45 would you be able to pull the logs for them?

**Comment by robkoehler45** [comment]
@kpsuperplane fixed! I’m seeing my 11 lights now.  I’ll start a new issue if I find anything else as I go through setting up and using them.
