### ISSUE TITLE
No Response HomeBridge in Docker 

### ISSUE THREAD

**Issue by hugocarmona7** [kpsuperplane/homebridge-wiz-lan#72]
Hello Guys 

I'm trying this plug-in with no success. Here's my config file `{
"platform": "WizSmarthome",
"name": "Wiz",
"port": 38899,
"broadcast": "255.255.255.255",
"address": "192.168.8.232",
"devices": [
        { "host": "192.168.8.154" }
      ]
    }`
And Always get the same in Home App: No response. 
HomeBridge doesn't show any logs to debug, I did try also with 38900 port with the same result. 

Any ideas? 

![image](https://user-images.githubusercontent.com/25641898/131422714-eafe818b-73c4-4731-9d5f-a6b5fc665831.png)

This is my platform 

![image](https://user-images.githubusercontent.com/25641898/131422984-04139b91-19db-47bf-b613-e547ddaa49aa.png)

In Home Assistant this plug-in is working perfect. 
https://github.com/sbidy/wiz_light

**Comment by kpsuperplane** [comment]
Unfortunately this is hard to troubleshoot without logs. If you don't mind, can you try running it again on the latest version with Homebridge debug mode enabled? https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting
