### ISSUE TITLE
Plugin won't install

### ISSUE THREAD

**Issue by ianwilliamryan** [kpsuperplane/homebridge-wiz-lan#73]
I apologise in advance if this issue seems juvenile, I am a novice at all this.

I recycled power to my raspberry pi last night and I lost all my plugins. I have reinstalled most of them and have everything back to normal. But I cannot get "homebridge-wiz-lan" to install. See attached screenshot of message. I went to the terminal to try and get the debug log but it gives me a permission denied message.

Any help or advice for this
<img width="803" alt="Screenshot 2021-09-18 at 12 24 16" src="https://user-images.githubusercontent.com/90965713/133887331-25454b7c-521f-4513-a371-b385f4af7495.png">
?

**Comment by kpsuperplane** [comment]
Unfortunately I think this is something wrong with your node install. did you ever figure it out?
