### ISSUE TITLE
Issue when Light Ip changes

### ISSUE THREAD

**Issue by beyersito** [kpsuperplane/homebridge-wiz-lan#75]
Hi! I have been using the plugin and found an issue that I believe is related to the lightbulb ip. Sometimes after a while or after turning on/off power the lights change IP address, and from debugging the plugin I found that the IP is not updated. I tried to scan the code to investigate where this change should live but I've never worked with Homebridge. I can take the issue if someone can provide guidance. Thanks

**Comment by aralam** [comment]
It is a good practice to have your home router issue fixed IP address for IoT devices (like smart bulbs). Dynamic IP address breaks whole bunch of configs and make troubleshooting challenging. This can be achieved by using a feature called DHCP reservation. Google your router’s make/model on how to perform this config.
