### ISSUE TITLE
Missing Scene Option after homebridge server restart

### ISSUE THREAD

**Issue by dptech70** [kpsuperplane/homebridge-wiz-lan#76]
I successfully installed and I am using this plugin on 8 Wiz RGB Bulbs A19 and BR30. When I initially installed I had the scene options on all bulbs. Once I had to restart the homebridge server I lost the scene option on all bulbs except one A19 bulb. If I remove the bride and add to home kit fresh they will all have the option again. I also see this error in the log after restart:

[10/9/2021, 9:15:38 PM] [@krystofcelba/homebridge-wiz-lan] This plugin generated a warning from the characteristic 'Brightness': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.

![IMG_3064](https://user-images.githubusercontent.com/18035672/136679293-15782d43-24f9-485b-b27b-201dff958c07.JPG)
![IMG_3065](https://user-images.githubusercontent.com/18035672/136679295-a0e30db6-c4e2-4f05-9143-c4892bcbd1e3.JPG)

**Comment by kpsuperplane** [comment]
Should be fixed in the latest update, please open another issue if this perists.

**Comment by dptech70** [comment]
Thank you. I will give it a try.
