### ISSUE TITLE
Feature request: Support for Wiz plugs

### ISSUE THREAD

**Issue by SenneValvekens** [kpsuperplane/homebridge-wiz-lan#77]
Hi. Would it be possible to add support for Wiz plugs? I currently get a message saying "Unknown device [object Object], skipping..." in HomeBridge.

I'm not sure how much work it would be to add support for this, but it would just need an on or off switch.

Kind Regards.

**Comment by ricbacca** [comment]
Hi.
Also i'm interested in this issue.
I'm currently getting the same message in HomeBridge logs.

it would just need an on or off switch.

Thanks.
