### ISSUE TITLE
Same Type of Light Two Different Menus in HomeKit

### ISSUE THREAD

**Issue by jodywhitesides** [kpsuperplane/homebridge-wiz-lan#78]
I'm using two Wiz A21 lights. For some reason, one of the lights has the 'scene' menu in the "Light" area: see image
![IMG_419F7E5E5E95-1](https://user-images.githubusercontent.com/93063182/138577306-68aa9132-6be8-4090-bc5f-4f9db311acc1.jpeg)

The other light is not showing the 'scenes' from Wiz in "Light":
![IMG_4266F862BF70-1](https://user-images.githubusercontent.com/93063182/138577326-0f63cf96-d556-499e-bbb8-79119bec0a18.jpeg)

Wondering how I can get the 2nd light to show the 'scenes' menu from Wiz? Without that scenes menu, the light refuses to work properly in HomeKit.

Both devices are listed in Homebridge and have their proper IP addresses in the config. Is there another setting for the config that I should be using for the individual lights?

**Comment by Gryzle** [comment]
I just wanted to add that I'm also experiencing this bug. Thanks for your support, Developer!

**Comment by kpsuperplane** [comment]
The latest update should fix this, can anyone confirm?

**Comment by jodywhitesides** [comment]
Is this the new version: homebridge-wiz-lan v3.1.2 (2021-11-12)?

**Comment by MoTechnicalities** [comment]
This is not an issue anymore. Each light now has the same available menus.

Each light has 2 accessories (tiles) that can be separated, if you want that separate functionality. I prefer displaying the lights as one tile, even though it means loosing one click ON/OFF functionality. Instead, the first click opens the accessory settings.

In there any way to program it so only a long hold click opens the accessory settings menu, while a shot click just turns the accessory ON/OFF when displayed as one tile?

**Comment by jodywhitesides** [comment]
Is there a way to uninstall the v4.0.1

**Comment by kpsuperplane** [comment]
Glad to hear, closing the issue. Please feel free to file another one if something comes up!

Thank you for the support :)

**Comment by kpsuperplane** [comment]
Also @MoTechnicalities unfortunately I do not see any provision in homebridge to set the "single click" action. Would love to be proven wrong though...

**Comment by jodywhitesides** [comment]
I only get 1 tile per light and no scene menus now... :-(

**Comment by kpsuperplane** [comment]
@jodywhitesides yup, you need to enable the scenes in the config.

**Comment by jodywhitesides** [comment]
Got it, thank you. Missed that setting. Now they're working quite well with HomeKit.
