### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by j-ktz** [kpsuperplane/homebridge-wiz-lan#79]
I installed the plugin and did the simple configuration and saved. The config shows:

`{
    "platform": "Wiz Lan"
}`

I can add the Bridge to Homekit, but the bulbs don't show up even though I can see them in the Wiz app?

**Comment by dhruvb14** [comment]
I am also having same issue and I had been configured and working for last 6 months and now it doesn't work anymore. I wonder if there was a WIZ firmware upgrade

**Comment by Jendker** [comment]
It may be specific to your setup. I just freshly installed the plug-in (uninstall, system restart, install, system restart) and everything works as expected. If there is a way to check what is my lights firmware version to confirm it for you, please let me know.

**Comment by jimyson** [comment]
Check this out from @bwp91.  Worked for me.
[https://github.com/hoobs-org/HOOBS/issues/1651](url)

**Comment by kpsuperplane** [comment]
Does the latest update fix this?
