### ISSUE TITLE
Turn on/off does not start with the same colors set with HomeKit and app

### ISSUE THREAD

**Issue by Jendker** [kpsuperplane/homebridge-wiz-lan#80]
I like to control the light colors with the app because of all the color presets and the nice Rhythms feature. The problem is that if I turn on the light with HomeKit afterwards, then the light bulb activates with the color it was previously set with HomeKit, not the last setting on the light bulb. Similarly the app doesn’t activate the light with the last color set with HomeKit. Instead of just turning on the light with its last setting (be it the color/white set with HomeKit or the app) it remembers the color which was last set with the same control input.

Do you think it’s possible to unify the light control between the HomeKit and the app? I was trying to go over the repo code but could not identify what is causing this separation.

**Comment by Jendker** [comment]
There is actually no such issue on the other, 3.0.4 plug-in version from the NPM. Everything is smooth.

**Comment by dchakro** [comment]
I have the same issue on v3.2.0. @Jendker  how did you manage to resolve it ?

**Comment by Jendker** [comment]
I should probably reopen the issue because it still persists. I was too eager on closing this.
