### ISSUE TITLE
WIZLAN - can't find any lights

### ISSUE THREAD

**Issue by dipen26** [kpsuperplane/homebridge-wiz-lan#89]
I tried both configuration options, but non seems to find any light. I am using TP Link Deco to connect all lights. Please suggest any solution. Thank you

**Comment by MoTechnicalities** [comment]
Did you configure the plugin settings to use the IP address of your bulb, as listed in the WIZ App?

Note: you first need to configure your router to reserve the IP address to use for that device.

**Comment by dipen26** [comment]
I used IP address from the app, and reversed all the IPs on router, but still nothing shows up on Hoobs.

**Comment by kpsuperplane** [comment]
Which bulbs do you have?
