### ISSUE TITLE
Can't keep my light's names

### ISSUE THREAD

**Issue by djcrawleravp** [kpsuperplane/homebridge-wiz-lan#90]
Everytime my bridge restarts, My lights go back to it's factory names, and have to change it back manually, breaking my scenes and alexa routines.

By the way, Alexa always recognize the lights as new leaving the "old" ones as inactive

All my devices are DHCP reserved 

My json

{
    "platform": "WizSmarthome",
    "name": "Wiz",
    "enableScenes": true,
    "address": "192.168.0.5",
    "devices": [
        {
            "host": "192.168.0.34",
            "name": "Luz de Vivi",
            "mac": "6C:29:90:D3:5B:D0"
        },
        {
            "host": "192.168.0.35",
            "name": "Lampara",
            "mac": "6C:29:90:D2:C9:1B"
        },
        {
            "host": "192.168.0.36",
            "name": "Luz de Alonso",
            "mac": "6C:29:90:D3:E8:C9"
        }
    ],
    "_bridge": {
        "username": "0E:19:B3:4A:0F:9B",
        "port": 46793
    }
}

**Comment by kpsuperplane** [comment]
I suspect this might be your homebridge setup not caching the devices correctly
