### ISSUE TITLE
only one lamp shows up

### ISSUE THREAD

**Issue by moraro07** [kpsuperplane/homebridge-wiz-lan#91]
So I connected the lamp in the kitchen. My other AEG Wiz Markos doesn't show up.
At least not in Homebridge. The Wiz App works fine and I even tried addressing the lamp via the IP address.
They are in the same subnet.

**Comment by kpsuperplane** [comment]
Unfortunately the AEG Wiz Markos is currently not supported. While I suspect the existing API might just work, I don't have one to test with (nor do I have the unique identifier of the product). 

Please feel free to play with it and submit a PR though!
