### ISSUE TITLE
Run Scene Service Tile Only?

### ISSUE THREAD

**Issue by MoTechnicalities** [kpsuperplane/homebridge-wiz-lan#94]
When running the service with the scene option, we currently have two tiles for each bulb. But, we are somehow losing grouping and quick tile press for ON/OFF functionality. 

So, I am wondering if it would be possible to modify the plugin to just run the bulb's service tile only and disable the other tile, so that we have the scene capability, but then add dimming and color selection capability to the scene tile.

Essentially building upon the scene service part of the plug-in to provide the full range of custom features for each WIZ bulb, including scene selection, dimming, color, and grouping. All from the one tile.

Is this out of the range of what is possible?

**Comment by kpsuperplane** [comment]
Unfortunately, different services (in this case Lightbulb + TV Service) only support specific features. Thus it isn't possible to attach color selection to a TV service, or a TV Input selector to a lightbulb.
