### ISSUE TITLE
Spex Switches?

### ISSUE THREAD

**Issue by bradders** [kpsuperplane/homebridge-wiz-lan#95]
I'm trying to use homebridge-wiz-lan to connect my Spex switches (which claim to be Wiz connected) to Hoobs but I'm getting a "device not supported" warning in my logs.

`2022-01-05, 9:10:22 PM Wiz Lan Bridge WizSmarthome WARNING Unknown device ESP11_DIMTRIACS_01, skipping...`
`2022-01-05, 9:14:12 PM Wiz Lan Bridge WizSmarthome WARNING Unknown device ESP11_3WAYSWITCH_01, skipping...`

I get one error per switch, and this happens even when I manually add the device IPs in config.

FWIW: this is the switch that won't connect ... https://spexlighting.com/collections/smart-devices-accessories-1/products/smart-dimmer-switch

**Comment by bradders** [comment]
@kpsuperplane Just digging around the code now, it seems current support is only for Wiz bulbs and sockets. Is there any plans to add something similar to this PR, but for switches? https://github.com/kpsuperplane/homebridge-wiz-lan/commit/fa77be5327cc27b0918b3bd5232aae5bae5a0ce3

**Comment by kpsuperplane** [comment]
Hey @bradders, thanks for the submission. Unfortunately I don't have a Spex switch to test on, and it likely has different protocols than that of the bulbs. 

Please feel free to submit a PR though if you wanna tinker with it yourself.
